### ISSUE TITLE
Pandas DF structure for test_df and train_df

### ISSUE THREAD

**Issue by Philip030601** [K-Ibadullaev/py-ssa-lib#22]
Thank you for making a library to determine ssa, mssa, and many other functions.  I look forward to learning how to use it and apply it.  I am having an issue with the structure of the pandas dataframe required by the library.  My pandas df is structured similar to your GlobalLandTemperatureByMajorCity with the row labels on the left most column and the column labels on the top of each column.  For this pandas dataframe structure, how should the train_df and test_df be structrured so that the library accepts the train_df and test_df and perform its functions.  I would much appreciate any assistance you can provide.  Much thanks again.  

```![image](https://github.com/user-attachments/assets/c0382741-0aea-4c84-9bad-a3810c235d15)
 ```

**Comment by K-Ibadullaev** [comment]
Hello @Philip030601, I don't see the content of a code cell below your comment. The structure of pandas data frame depends on the class of SSA you are using but generally follows the wide format, that is, column names contain dates when the values a variable of interest(e.g Average Temperature)  were recorded. 

In the simplest univariate case  you should have a pandas data frame having shape of 1 row and n columns for SSA. Splitting that data set can be achieved by slicing, e.g ` df.iloc[:, : int(0.9*df.shape[1]) ] `and `df.iloc[:, int(-0.1*df.shape[1]): ]` 

However, it is also possible to pass starting index of the row(ts parameter) and column(idx_start_ts), which containins first numeric value of the time series. 


Take a look on screenshots I attached to this comment.


![berlin1](https://github.com/user-attachments/assets/673549a9-ba50-4857-abc0-01051c927648)
![berlin2](https://github.com/user-attachments/assets/ed1d77b7-96f0-4fc0-abdf-1683abd9bd15)
![berlin3](https://github.com/user-attachments/assets/17a642b4-a76c-435b-a97a-65ca4dc5fe81)
![berlin4](https://github.com/user-attachments/assets/864d96d5-453a-4f73-abbf-578e3941658e)

I intend to upload a notebook with examples using this data set later on. At the moment you can either follow steps on the screenshots or jupyter notebooks with the guide for each class and make use of `help(your_ssa_instance.fit())` . Hope it would help you!

**Comment by Philip030601** [comment]
> Hello @Philip030601, I don't see the content of a code cell below your comment. The structure of pandas data frame depends on the class of SSA you are using but generally follows the wide format, that is, column names contain dates when the values a variable of interest(e.g Average Temperature) were recorded.
> 
> In the simplest univariate case you should have a pandas data frame having shape of 1 row and n columns for SSA. Splitting that data set can be achieved by slicing, e.g `df.iloc[:, : int(0.9*df.shape[1]) ]`and `df.iloc[:, int(-0.1*df.shape[1]): ]`
> 
> However, it is also possible to pass starting index of the row(ts parameter) and column(idx_start_ts), which containins first numeric value of the time series.
> 
> Take a look on screenshots I attached to this comment.
> 
> ![berlin1](https://private-user-images.githubusercontent.com/108762356/396247750-673549a9-ba50-4857-abc0-01051c927648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjkxMjAsIm5iZiI6MTczNDQ2ODgyMCwicGF0aCI6Ii8xMDg3NjIzNTYvMzk2MjQ3NzUwLTY3MzU0OWE5LWJhNTAtNDg1Ny1hYmMwLTAxMDUxYzkyNzY0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTA5ZDc1MWNjOTc0NjkxMjY1Y2FmZGM0MzM2OWYzNzllYTlkNzhmMGYwZDhmMThjYzVjZjU3MTJmMDIzZDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7G0EjdNKRbzImC1a1lix_zn222i-CmF1-gmNCuzYiK8) ![berlin2](https://private-user-images.githubusercontent.com/108762356/396247756-ed1d77b7-96f0-4fc0-abdf-1683abd9bd15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjkxMjAsIm5iZiI6MTczNDQ2ODgyMCwicGF0aCI6Ii8xMDg3NjIzNTYvMzk2MjQ3NzU2LWVkMWQ3N2I3LTk2ZjAtNGZjMC1hYmRmLTE2ODNhYmQ5YmQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjgxMTg0ZTY4ZDJhYzAxZmIyNzIzYTRjNThlMzFjOGViNGFmZjRkMjI0OWVjN2VlZjk2OWYxZmI0OGFjYTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N_H606AUGE-kNuhRn1DfN1RyJzw58rlcAAv2jq9eNxY) ![berlin3](https://private-user-images.githubusercontent.com/108762356/396247760-17a642b4-a76c-435b-a97a-65ca4dc5fe81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjkxMjAsIm5iZiI6MTczNDQ2ODgyMCwicGF0aCI6Ii8xMDg3NjIzNTYvMzk2MjQ3NzYwLTE3YTY0MmI0LWE3NmMtNDM1Yi1hOTdhLTY1Y2E0ZGM1ZmU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWZhMmI1MmRjMjQzNDdjZmZhOGM5MTUyZmFkOTg4YjVmODk4YmRhMzJlZjMyMWVjOWNmMGFiYjIxYWZlOWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-uK2K0-0iydTs1IGAm6Pm7wj4GjiHgLUTs-_o0wA9J4) ![berlin4](https://private-user-images.githubusercontent.com/108762356/396247763-864d96d5-453a-4f73-abbf-578e3941658e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjkxMjAsIm5iZiI6MTczNDQ2ODgyMCwicGF0aCI6Ii8xMDg3NjIzNTYvMzk2MjQ3NzYzLTg2NGQ5NmQ1LTQ1M2EtNGY3My1hYmJmLTU3OGUzOTQxNjU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmU3ZGIyOTg1M2JjNTA5YWI4NjUyMzAyZTg5NzQzOTM3YzY4ZDljZmViYWMyYzQwOWM2OTM5NzM0NzEyODNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zy4pmddUVmPjTvvmSXUO0zB2L5niS6K8kEY9eVdy_Hw)
> 
> I intend to upload a notebook with examples using this data set later on. At the moment you can either follow steps on the screenshots or jupyter notebooks with the guide for each class and make use of `help(your_ssa_instance.fit())` . Hope it would help you!

Hi K-Ibadullaev,  Thanks for the response and insight.  I will rearrange my df as you stated and run it again.  Also, I will try to change the following code "df.iloc[:, : int(0.9*df.shape[1]) ]and df.iloc[:, int(-0.1*df.shape[1]): ]" to filter my original df by chaging the first part of the iloc function since most of the data df have the date on the first column in rows as an index.  I will get back to you if I get it to work.  Should have noticed that previously.  Thanks again.
